PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix RO: <http://purl.obolibrary.org/obo/RO_>
prefix HP: <http://purl.obolibrary.org/obo/HP_>
prefix PATO: <http://purl.obolibrary.org/obo/PATO_>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix def: <http://purl.obolibrary.org/obo/IAO_0000115>
prefix owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# Get all classes related to diseases that 
SELECT DISTINCT ?parent ?parent_label ?entity ?entity_label WHERE
{
  
  ?parent rdfs:subClassOf+ PATO:0000001 .
  ?parent oio:inSubset <http://purl.obolibrary.org/obo/pato#attribute_slim> .
  ?entity rdfs:subClassOf+ ?parent .
  ?entity rdfs:label ?entity_label .
  ?parent rdfs:label ?parent_label .
  
  FILTER NOT EXISTS {
  	?entity oio:inSubset <http://purl.obolibrary.org/obo/pato#attribute_slim> .
  }

  FILTER(STRSTARTS(STR(?entity), "http://purl.obolibrary.org/obo/PATO_"))
  FILTER(STRSTARTS(STR(?parent), "http://purl.obolibrary.org/obo/PATO_"))
  FILTER(STRENDS(STR(?entity_label), CONCAT(" ",STR(?parent_label))))
}
  