 % -- ********************************************************* --
 % -- Autogenerated Prolog factfiles 
 % -- see http://www.blipkit.org for details 
 % -- ********************************************************* --

ontology('oba/imports/pr_import').

metadata_db:entity_label('BFO:0000030', 'object').
class('BFO:0000030').
subclass('BFO:0000030', 'BFO:0000040').

metadata_db:entity_label('BFO:0000040', 'material entity').
class('BFO:0000040').

metadata_db:entity_label('CHEBI:23367', 'molecular entity').
class('CHEBI:23367').
subclass('CHEBI:23367', 'BFO:0000030'). % object

metadata_db:entity_label('GO:0005575', 'cellular_component').
class('GO:0005575').
subclass('GO:0005575', 'BFO:0000030'). % object

metadata_db:entity_label('GO:0005886', 'plasma membrane').
class('GO:0005886').
subclass('GO:0005886', 'GO:0005575'). % cellular_component

metadata_db:entity_label('PR:000000001', 'protein').
class('PR:000000001').
subclass('PR:000000001', 'PR:000018263').

metadata_db:entity_label('PR:000001091', 'interleukin-1').
class('PR:000001091').
subclass('PR:000001091', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000001092', 'interleukin-17').
class('PR:000001092').
subclass('PR:000001092', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000001135', 'interleukin-1 alpha').
class('PR:000001135').
subclass('PR:000001135', 'PR:000001091'). % interleukin-1

metadata_db:entity_label('PR:000001136', 'interleukin-1 beta').
class('PR:000001136').
subclass('PR:000001136', 'PR:000001091'). % interleukin-1

metadata_db:entity_label('PR:000001317', 'interleukin-7').
class('PR:000001317').
subclass('PR:000001317', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000001335', 'class 2 cytokine, IL-10 type').
class('PR:000001335').
subclass('PR:000001335', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000001370', 'interleukin-13').
class('PR:000001370').
subclass('PR:000001370', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000001373', 'interleukin-15').
class('PR:000001373').
subclass('PR:000001373', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000001374', 'interleukin-16').
class('PR:000001374').
subclass('PR:000001374', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000001376', 'interleukin-18').
class('PR:000001376').
subclass('PR:000001376', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000001379', 'interleukin-2').
class('PR:000001379').
subclass('PR:000001379', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000001382', 'interleukin-21').
class('PR:000001382').
subclass('PR:000001382', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000001387', 'interleukin-3').
class('PR:000001387').
subclass('PR:000001387', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000001391', 'interleukin-4').
class('PR:000001391').
subclass('PR:000001391', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000001392', 'interleukin-5').
class('PR:000001392').
subclass('PR:000001392', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000001393', 'interleukin-6').
class('PR:000001393').
subclass('PR:000001393', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000001396', 'interleukin-9').
class('PR:000001396').
subclass('PR:000001396', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000001471', 'interleukin-10').
class('PR:000001471').
subclass('PR:000001471', 'PR:000001335'). % class 2 cytokine, IL-10 type

metadata_db:entity_label('PR:000001848', 'butyrophilin').
class('PR:000001848').
subclass('PR:000001848', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000003766', 'perilipin-2').
class('PR:000003766').
subclass('PR:000003766', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000005940', 'alpha-S1-casein').
class('PR:000005940').
subclass('PR:000005940', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000005941', 'beta-casein').
class('PR:000005941').
subclass('PR:000005941', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000005942', 'kappa-casein').
class('PR:000005942').
subclass('PR:000005942', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000007581', 'fibronectin').
class('PR:000007581').
subclass('PR:000007581', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000009649', 'alpha-lactalbumin').
class('PR:000009649').
subclass('PR:000009649', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000009758', 'leptin').
class('PR:000009758').
subclass('PR:000009758', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000009978', 'lactotransferrin').
class('PR:000009978').
subclass('PR:000009978', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000011374', 'atrial natriuretic factor').
class('PR:000011374').
subclass('PR:000011374', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000013429', 'parathyroid hormone').
class('PR:000013429').
subclass('PR:000013429', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000013883', 'renin').
class('PR:000013883').
subclass('PR:000013883', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000015763', 'erythrocyte band 7 integral membrane protein').
class('PR:000015763').
subclass('PR:000015763', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000016261', 'serotransferrin').
class('PR:000016261').
subclass('PR:000016261', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000017467', 'whey acidic protein').
class('PR:000017467').
subclass('PR:000017467', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000018263', 'amino acid chain').
class('PR:000018263').
subclass('PR:000018263', 'CHEBI:23367'). % molecular entity

metadata_db:entity_label('PR:000018932', 'angiotensinogen proteolytic cleavage product').
class('PR:000018932').

metadata_db:entity_label('PR:000023540', 'alkaline phosphatase').
class('PR:000023540').
subclass('PR:000023540', 'PR:000000001'). % protein

metadata_db:entity_label('PR:000036009', 'angiotensin II').
class('PR:000036009').
subclass('PR:000036009', 'PR:000018932'). % angiotensinogen proteolytic cleavage product

